---
- name: load architecture-dependent configuration
  include_vars:
    file: "vars/config_{{ ansible_architecture }}.yml"

- import_tasks: get-version.yml
- import_tasks: stop-services.yml
  when: install_adguardhome
- import_tasks: install-adguardhome.yml
  when: install_adguardhome
- import_tasks: start-services.yml
  when: install_adguardhome
- import_tasks: cleanup.yml
  when: install_adguardhome

